### PR TITLE
Modman file added

### PR DESCRIPTION
**Pull request by vovayatsyuk**
Added ability to install extension using [modman tool](https://github.com/colinmollenhour/modman):

``` bash
modman clone git@github.com:razorpay/razorpay-magento.git -b master
```

### CODE REVIEW

**Comment by shashankkumar** [comment]
@73sl4 any update here?

**Comment by 73sl4** [comment]
@vovayatsyuk We have updated our plugin. Can you fast forward your branch and file an updated PR.

**Comment by vovayatsyuk** [comment]
@73sl4 Done.

**Comment by mayankamencherla** [comment]
@ccrims0n Can we merge this?

**Pull request merged**
