### PR TITLE
Added support for Razorpay Extended Config Data

### PR DESCRIPTION
**Pull request by sachin000**
- API Key & Merchant Name are **required** for front end integration

### CODE REVIEW

**Comment by ramth05** [comment]
@sachin000 ,  Can you please provide some screen shots to understand why this change required.
and steps to test it.

**Comment by sachin000** [comment]
**https://razorpay.com/docs/payment-gateway/web-integration/standard/checkout-options/**

As per above documentation **Name** & **Key** parameters are required for front end integration and it should come from backend Magento configurationRight now they are not exposed. They should be exposed as per Magento store config graphql 

**https://devdocs.magento.com/guides/v2.4/graphql/queries/store-config.html**

For example, see how its implemented in Paypal graphql support for Magento

**https://github.com/scandipwa/paypal-graphql/blob/master/src/etc/graphql/di.xml**

This way, this config will be available when Magento store config graphql endpoint is invoked.  

**Note**: without this implementation API key & Merchant name must be hard coded in front end code, which is not the right way

**Comment by sachin000** [comment]
As a test case, this Graphql query should work (which is right now throwing error). My PR is a fix for this issue.

Screenshot 2021-08-05 at 11 46 59 AM
)

**Comment by ramth05** [comment]
> As a test case, this Graphql query should work (which is right now throwing error). My PR is a fix for this issue.
> 
> Screenshot 2021-08-05 at 11 46 59 AM
> )

@sachin000 , looks fine you want that info to be fetched in your front-end app. Thanks!

**Review by ramth05 — APPROVED** [review]
LGTM

**Comment by sachin000** [comment]
Additional Code Fix 
Screenshot 2021-08-05 at 5 35 06 PM
 
https://github.com/razorpay/razorpay-magento/pull/268

**Comment by sachin000** [comment]
Code Fix
https://github.com/razorpay/razorpay-magento/pull/268

Screenshot 2021-08-05 at 5 35 58 PM

**Pull request merged**
